name: Run Robot Framework Login Test

on:
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r selenium_robot_login_project/requirements.txt
        pip install selenium==4.11.2  # ✅ Explicit version that works well with Chrome in GitHub Actions

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Run Robot Framework tests
      run: |
        robot selenium_robot_login_project/tests/LoginTest.robot


